### ISSUE TITLE
Stealth for druid

### ISSUE THREAD

**Issue by NBerd** [bhhandley/CleveRoidMacros#2]
Hello. I write macro for my druid

#showtooltip
/cast [stealth] Pounce; Rake

Looks like [stealth] not working

**Comment by bhhandley** [comment]
Are on the latest version?  I fixed an issue with that a few days ago.  Otherwise, what language is your game in?

**Comment by NBerd** [comment]
Yes, the latest version. I play on turtle wow, on the English version. In the roid-macro version it works. But it's not in your version. And I would like to see a dynamic tooltip, as you have implemented

**Comment by bhhandley** [comment]
https://github.com/user-attachments/assets/856a1579-95ee-4674-a630-42af22e6c7e9

Oh -- do you have superwow?  For the most part, player buffs require that and I changed some things around because there were several different things looking up buffs and whatnot in different ways.  I wanted to simply it for myself for now at least.  

If that's the issue, I'd recommend that and nampower if you want full functionality like range checking and better targeting support.

**Comment by NBerd** [comment]
Nice. Thanks, i think this is the solution

**Comment by bhhandley** [comment]
Superwow or the changes?

**Comment by NBerd** [comment]
Superwow. But it would be great if you implement the changes. Too lazy to understand mods. Maybe there are similar people

**Comment by bhhandley** [comment]
Understandable but both of those mods give a lot better functionality to vanilla so I'd still recommend them -- they're both linked on the README.  Just need to use something like Vanilla Fixes to start wow instead of the launcher.  In any case, I pushed the changes so it should work for you now regardless.  

Please test and let me know if it's working for you.

**Comment by NBerd** [comment]
Nah :(

/cast  [stealth] Pounce; Rake

Always use Rake

**Comment by bhhandley** [comment]
Well, that's what happens without sleep.  Should be working now, let me know.

**Comment by NBerd** [comment]
Works great, thanks! Don't overwork yourself. Thanks again for your work

**Comment by bhhandley** [comment]
No worries, happy holidays.
